# .eslintrc.yaml

env:
  # browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

ignorePatterns:
  - node_modules
  - dist

parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  sourceType: "module"

plugins:
  - "@typescript-eslint"
# rules:
# Add any additional rules or overrides here
